# This file was generated by GoReleaser. DO NOT EDIT.
cask "internctl" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "4b54da92a00ad275de9483756d814e4f6545a58b936aa241fa62d7f6a8898852"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "496dcfc40bdc39fad50e139f048f826779b6f5d080e68d2ef20ed81cc80de3ca"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "de67d6ab3f4d3becf3f027f35a38f2597c7d2b99315fc4660506560d4aff3241"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2b260b63765925bbee083187c03d9e3f14f0c0f62997d175021046c08f3a219"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "internctl"
  desc "Command-line client for Intern"
  homepage "https://github.com/sbekti/intern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "internctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/internctl"]
    end
  end

  # No zap stanza required

end
