# This file was generated by GoReleaser. DO NOT EDIT.
cask "internctl" do
  version "0.4.5"

  on_macos do
    on_intel do
      sha256 "089440c9e61ef0ad82567aa98f591461c34e7236b85ac5c18a310dae9ac93e3a"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cd3b1db885c19229235a41f06339eb58d209dc3e0aaa45dc28ca5b8486c2dc7"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1aac450e441bac8d53094a0165d9b3ee49ff7c302261f50381ac758418ac3a7e"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "590d035806128fde915e15d3622aa60794fba7ccf575fc95cc31f670c2fe4130"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "internctl"
  desc "Command-line client for Intern"
  homepage "https://github.com/sbekti/intern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "internctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/internctl"]
    end
  end

  # No zap stanza required

end
