# This file was generated by GoReleaser. DO NOT EDIT.
cask "internctl" do
  version "0.4.10"

  on_macos do
    on_arm do
      sha256 "d965f47d3013d5de02c3e7572e821c171bbfcb488d73da9e6feb71265370e5f0"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "55204fc45589af090bc275a91cd33517cc65d87d57ce925b6dd69c86441b7e48"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3e313ffb3c1067714c0ff267f99362a1407831fdc85d98609e397ff30432a24b"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a87efa6a1dbbc089d484ec0925aa4b4bd917637eb092b90fe4e323ddbc936564"
      url "https://github.com/sbekti/intern/releases/download/v#{version}/internctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "internctl"
  desc "Command-line client for Intern"
  homepage "https://github.com/sbekti/intern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "internctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/internctl"]
    end
  end

  # No zap stanza required
end
