# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Internctl < Formula
  desc "Command-line client for the internal management platform"
  homepage "https://github.com/sbekti/internctl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sbekti/internctl/releases/download/v0.1.1/internctl_0.1.1_darwin_amd64.tar.gz"
      sha256 "f9de77a557d7d2073192773c5d7a18b1d759c9e2fa963320c598e3939265ea0a"

      define_method(:install) do
        bin.install "internctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sbekti/internctl/releases/download/v0.1.1/internctl_0.1.1_darwin_arm64.tar.gz"
      sha256 "5daaec172de0ed6811c477389901aa7410a7d22d17ffdfc9fb39bbc3e2637016"

      define_method(:install) do
        bin.install "internctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbekti/internctl/releases/download/v0.1.1/internctl_0.1.1_linux_amd64.tar.gz"
      sha256 "8372984726f1eaa520e82dec51d1c5cf915c4f81375f7ed4872d4fc947acb8c9"
      define_method(:install) do
        bin.install "internctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sbekti/internctl/releases/download/v0.1.1/internctl_0.1.1_linux_arm64.tar.gz"
      sha256 "fa37f0c98d414e16467fe472920a4d9d176976e12e875a8fe947cc8121551acf"
      define_method(:install) do
        bin.install "internctl"
      end
    end
  end

  test do
    system "#{bin}/internctl", "--version"
  end
end
